version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: reward-mysql
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=reward
      - MYSQL_USER=reward
      - MYSQL_PASSWORD=rewardkjkj
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_volume:/var/lib/mysql
    # networks:
    #   - reward-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 10

  # redis:
  #   image: redis:alpine
  #   container_name: reward-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - reward-network
  #   command: redis-server --appendonly yes
  #   restart: always

  # minio:
  #   image: minio/minio:latest
  #   container_name: reward-minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     - MINIO_ROOT_USER=minioadmin
  #     - MINIO_ROOT_PASSWORD=minioadmin
  #   volumes:
  #     - minio_data:/data
  #   command: server --console-address ":9001" /data
  #   networks:
  #     - reward-network
  #   restart: always

volumes:
  mysql_volume:
    driver: local
  minio_data:

# networks:
#   reward-network:
#     driver: bridge