spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reward?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}
  devtools:
    restart:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

app:
  frontend:
    url: http://localhost:46151
  cookie:
    domain: localhost
    secure: false
    same-site: Lax
  backend:
    url: http://localhost:8080

naverpay:
  api:
    url: https://dev.apis.naver.com/naverpay-partner/naverpay/payments/v2.2
  success-url: http://localhost:8080/api/v1/payments/naver/success
  fail-url: http://localhost:8080/api/v1/payments/naver/fail
  cancel-url: http://localhost:8080/api/v1/payments/naver/cancel

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: reward-dev

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.outsider.reward: debug 