# Reward Server - Config Server 연결 설정
spring:
  application:
    name: reward # config server에서 사용할 애플리케이션 이름
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: 
      - optional:file:.env[.properties]
      - optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888} # config server에서 설정 가져오기
  
  # Kafka 설정 (config server에서 override 가능)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reward-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 5000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# AuthServer 연동 설정
authserver:
  base-url: http://localhost:8881

# YouTube API 설정 (Config Server에서 override 가능)
youtube:
  api:
    key: ${YOUTUBE_API_KEY:}
    base-url: https://www.googleapis.com/youtube/v3
    timeout: 30000
    max-retries: 3
# 참고: 모든 애플리케이션 설정은 Config Server에서 관리됩니다
# - 데이터베이스 설정 (spring.datasource.*)
# - JPA 설정 (spring.jpa.*)
# - Redis 설정 (spring.data.redis.*)
# - OAuth2 설정 (spring.security.oauth2.*)
# - 로깅 레벨 설정 (logging.level.*)
# - MinIO 설정 (minio.*)
# - 앱 설정 (app.*)
# - 결제 서버 연동 설정 (payment.*)
# Config Server 위치: config/config/reward/reward.yml, reward-prod.yml